name: autograding

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Autograding:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: "1"
    
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file ./dockerfile_github --tag autograde
    - run: docker run autograde
